Repository rapidsai/gpuci-build-environment, pull requests merged in 2020-10, with the labels that each got.

#132 FIX Generate locales on Ubuntu
  miniconda-cuda/Dockerfile
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, bug

#134 Add v0.17
  ci/axis/rapidsai-driver.yml
  ci/axis/rapidsai.yml
Labels: 3 - Ready for Review

#136 ENH Add Ubuntu 20.04 & CentOS 8 miniconda-cuda images
  ci/axis/miniconda-cuda.yml
  miniconda-cuda/Dockerfile
Labels: 3 - Ready for Review

#137 FIX Link root `.condarc` in `rapids` env
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, bug

#138 FIX Patch PR #137 by copying `.condarc` instead of symlink
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, bug

#139 FIX .condarc channel order
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 4 - Needs Reviewer, bug

#140 FIX Order nvidia channel before conda-forge
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, bug

#135 ENH Update conda to 4.8.3
  miniconda-cuda/Dockerfile
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 5 - Merge After Dependencies, conda

#141 Add CUDA 11.1 to miniconda-cuda-driver
  ci/axis/miniconda-cuda-driver.yml
Labels: 3 - Ready for Review

#142 Update axes to v0.17
  ci/axis/rapidsai-driver.yml
  ci/axis/rapidsai.yml
Labels: 3 - Ready for Review
