Repository rapidsai/gpuci-build-environment, pull requests merged in 2020-08, with the labels that each got.

#112 BUG Fix nvidia/cuda images that do not set CUDA_VERSION
  ci/axis/miniconda-cuda.yml
  ci/gpuci/run.sh
  miniconda-cuda/Dockerfile
Labels: 3 - Ready for Review, bug

#113 FIX Correct CUDA 11 version
  ci/axis/miniconda-cuda.yml
Labels: 3 - Ready for Review, bug

#115 ENH Remove `nomkl` from `rapids` conda env
  CONTRIBUTING.md
  legacy/miniconda-cuda-rapidsenv/Dockerfile
  legacy/miniconda-cuda-rapidsenv/Dockerfile.centos7
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, enhancement

#116 FIX Add 0.16 RAPIDS to nightly axis
  ci/axis/rapidsai-driver.yml
  ci/axis/rapidsai.yml
Labels: 3 - Ready for Review

#120 ENH Use nvidia/cuda for CUDA 10.2 & 11.0 Update 1
  ci/axis/miniconda-cuda.yml
Labels: 3 - Ready for Review, cuda

#121 ENH Disable 0.15 builds in 0.16 branch
  ci/axis/rapidsai-driver.yml
  ci/axis/rapidsai.yml
Labels: 3 - Ready for Review

#123 Disable cuda repo during yum update
  miniconda-cuda/Dockerfile
Labels: 3 - Ready for Review

#124 Disable cuda repo during yum update
  miniconda-cuda/Dockerfile
Labels: 3 - Ready for Review
