Repository rapidsai/gpuci-build-environment, pull requests merged in 2020-04, with the labels that each got.

#69 FIX Update versions and fix gcc update issue
  Dockerfile
  Dockerfile.centos7
Labels: 2 - In Progress

#68 [REVIEW] Use standard clang and clang-tools package instead of libclang
  Dockerfile
  Dockerfile.centos7
Labels: 0 - Blocked

#74 [REVIEW] Add shellcheck
  Dockerfile
  Dockerfile.centos7
  python3.5/Dockerfile
  python3.5/Dockerfile.centos7
Labels: 3 - Ready for Review
