Repository rapidsai/gpuci-build-environment, pull requests merged in 2021-04, with the labels that each got.

#172 Update rapidsai-driver.yml for v0.20 images
  ci/axis/rapidsai-driver.yml
Labels: 3 - Ready for Review

#173 FIX Enable CUDA 11.2 CentOS 7 builds
  ci/axis/miniconda-cuda.yml
  ci/axis/miniforge-cuda.yml
  ci/axis/rapidsai.yml
Labels: 3 - Ready for Review, cuda

#174 Don't install weak dependencies on centos
  builds-gcc7/Dockerfile.centos7
  miniconda-cuda/Dockerfile
  miniforge-cuda-l4t/Dockerfile
  miniforge-cuda/Dockerfile
  rapidsai/devel-centos.Dockerfile
Labels: 3 - Ready for Review

#176 ENH Update axis files for branch-0.20
  ci/axis/miniconda-cuda-driver.yml
  ci/axis/rapidsai-driver.yml
  ci/axis/rapidsai.yml
Labels: 3 - Ready for Review, enhancement

#177 ENH Add build Dockerfile for gcc9
  builds-gcc/Dockerfile.centos7-gcc7
  builds-gcc/Dockerfile.centos7-gcc9
Labels: 3 - Ready for Review, enhancement

#178 ENH Use gcc9 in gpuci/rapidsai images
  rapidsai/devel-centos.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, enhancement

#179 ENH Remove defaults channel from conda build
  CONTRIBUTING.md
  rapidsai-l4t/Dockerfile
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, enhancement

#180 ENH Remove conda defaults channel in dev environments
  rapidsai-l4t/Dockerfile
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos.Dockerfile
  rapidsai/devel.Dockerfile
Labels: enhancement
