Repository rapidsai/gpuci-build-environment, pull requests merged in 2021-02, with the labels that each got.

#153 ENH Update build stack to gcc/gxx 9
  ci/axis/rapidsai.yml
  ci/gpuci/run.sh
Labels: 5 - Merge After Dependencies, conda, containers

#159 FIX Update gcc7 builds to use gcc9 libstdc++.so
  builds-gcc7/Dockerfile.centos7
  miniconda-cuda/Dockerfile
  miniforge-cuda/Dockerfile
Labels: 3 - Ready for Review

#161 Fix miniforge docker image
  miniforge-cuda/Dockerfile
Labels: 3 - Ready for Review, bug

#162 FIX Update `conda clean` to remove all pkgs
  miniconda-cuda/Dockerfile
  miniforge-cuda/Dockerfile
  rapidsai/base-runtime.Dockerfile
  rapidsai/devel-centos7.Dockerfile
  rapidsai/devel.Dockerfile
Labels: 3 - Ready for Review, bug, conda
